export const USERS = 'users'
export const LOGIN_EMAIL = 'LOGIN_EMAIL'
export const LOGIN_PASSWORD = 'login_password'
export const CREATE_USER_USERNAME = 'create_user_username'
export const CREATE_USER_PASSWORD = 'create_user_password'
export const CREATE_USER_EMAIL = 'create_user_email'
export const FLAG_NEW_USER = 'flag_new_user'
